version: "3.5"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stadsarchief
      POSTGRES_USER: stadsarchief
      POSTGRES_PASSWORD: insecure
    volumes:
      - "~/.ssh/datapunt.key:/root/.ssh/datapunt.key"

  app:
    build:
      context: .
      target: app
    image: docker-registry.data.amsterdam.nl/datapunt/stadsarchief:${VERSION:-latest}
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY
    volumes:
      - ./src:/src
      - ./deploy:/deploy
    depends_on:
      - database

  dev:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    environment:
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      - DEBUG=true
      - SECRET_KEY=dev
      - PYTHONBREAKPOINT
    volumes:
      - ./src:/src
      - ./deploy:/deploy
    depends_on:
      - database
    entrypoint: /deploy/wait-for-it.sh database:5432 --
    command: python manage.py runserver 0.0.0.0:8000

  test:
    build:
      context: .
      target: tests
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    depends_on:
      - database
    environment:
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      - SECRET_KEY=insecure
      - DATABASE_NAME=stadsarchief
      - DATABASE_USER=stadsarchief
      - DATABASE_PASSWORD=insecure
    entrypoint: /deploy/wait-for-it.sh database:5432 --
